adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.oem.autotest
adb shell pm uninstall --user 0 com.oneplus.backuprestore.remoteservice
adb shell pm uninstall --user 0 com.oneplus.bttestmode
adb shell pm uninstall --user 0 com.oneplus.opbugreportlite
adb shell pm uninstall --user 0 com.oneplus.carrierlocation
adb shell pm uninstall --user 0 com.google.android.ims
adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb shell pm uninstall --user 0 cn.oneplus.oemtcma
adb shell pm uninstall --user 0 com.qualcomm.qti.cne
adb shell pm uninstall --user 0 com.android.backupconfirm
adb shell pm uninstall --user 0 com.android.ons
adb shell pm uninstall --user 0 com.example.tmo
adb shell pm uninstall --user 0 com.oem.logkitsdservice
adb shell pm uninstall --user 0 com.oneplus.factorymode.specialtest
adb shell pm uninstall --user 0 com.oneplus.sdcardservice
adb shell pm uninstall --user 0 com.oneplus.setupwizard
adb shell pm uninstall --user 0 com.qti.service.colorservice
adb shell pm uninstall --user 0 com.qualcomm.embms
adb shell pm uninstall --user 0 com.qualcomm.qti.dynamicddsservice
adb shell pm uninstall --user 0 com.qualcomm.qti.qtisystemservice
adb shell pm uninstall --user 0 com.qualcomm.qti.qwes.AndroidService
adb shell pm uninstall --user 0 com.qualcomm.qti.remoteSimlockAuth
adb shell pm uninstall --user 0 com.qualcomm.qti.uim
adb shell pm uninstall --user 0 com.qualcomm.qti.uimGbaApp
adb shell pm uninstall --user 0 com.qualcomm.uimremoteclient
adb shell pm uninstall --user 0 com.qualcomm.uimremoteserver
adb shell pm uninstall --user 0 net.oneplus.commonlogtool
adb shell pm uninstall --user 0 com.google.android.as
adb shell pm uninstall --user 0 com.google.android.apps.work.oobconfig
adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall --user 0 com.android.emergency
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.oneplus.factorymode
adb shell pm uninstall --user 0 com.google.android.documentsui
adb shell pm uninstall --user 0 com.oneplus.gamespace
adb shell pm uninstall --user 0 com.google.android.gms.location.history
adb shell pm uninstall --user 0 org.ifaa.aidl.manager
adb shell pm uninstall --user 0 net.oneplus.odm
adb shell pm uninstall --user 0 net.oneplus.odm.provider
adb shell pm uninstall --user 0 com.qualcomm.location
adb shell pm uninstall --user 0 com.qti.ltebc
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 cn.oneplus.nvbackup
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall --user 0 com.oneplus.camera.service
adb shell pm uninstall --user 0 com.oem.oemlogkit
adb shell pm uninstall --user 0 com.oneplus.backuprestore
adb shell pm uninstall --user 0 com.oneplus.collectiondata
adb shell pm uninstall --user 0 com.oneplus.diagnosemanager
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 net.oneplus.push
adb shell pm uninstall --user 0 com.quicinc.voice.activation
adb shell pm uninstall --user 0 com.oem.rftoolkit
adb shell pm uninstall --user 0 com.oneplus.screenrecord
adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb shell pm uninstall --user 0 com.qualcomm.qti.seccamservice
adb shell pm uninstall --user 0 com.android.traceur
adb shell pm uninstall --user 0 com.qualcomm.qti.uceShimService
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.oneplus.brickmode
